# Generated by Django 4.1 on 2022-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('post', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
